// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("KExtensions.Tests")]
[assembly: AssemblyCompany("k94ll13nn3")]
[assembly: AssemblyCopyright("Copyright © k94ll13nn3")]
[assembly: AssemblyProduct("KExtensions")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.15")]
[assembly: AssemblyInformationalVersion("0.1.0-ci0015")]
